
#ifndef K_TOUCH_H
#define K_TOUCH_H

#define WIFI_SCAN_INIT 0
#define WIFI_SCAN_COMPLETED 1

#define SENSORS_SCAN_INIT 0
#define SENSORS_SCAN_ING 1
#define SENSORS_SCAN_COMPLETED 2

#define HOTEND_SCAN_INIT 0
#define HOTEND_SCAN_ING 1
#define HOTEND_SCAN_COMPLETED 2
#define HOTEND_SCAN_ERROR 3


#define SWITCH_SCAN_INIT 0
#define SWITCH_SCAN_ING 1
#define SWITCH_SCAN_COMPLETED 2


#define FILE_SCAN_INIT 0
#define FILE_SCAN_ING 1
#define FILE_SCAN_COMPLETED 2
#define FILE_SCAN_PREPARE 3


#define PRINTNG_SCAN_INIT 0
#define PRINTNG_SCAN_ING 1
#define PRINTNG_SCAN_COMPLETED 2
#define PRINTNG_SCAN_FRIST 3
#define PRINTNG_SCAN_CANCEL 4

#endif