// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _KNOMI2_UI_H
#define _KNOMI2_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "rs_manage.h"
#define LV_IMG_DECLARE_FILE(var_name) extern lv_img_dsc_t var_name;

    LV_IMG_DECLARE_FILE(ui_img_CB1);
    LV_IMG_DECLARE_FILE(ui_img_complete);
    LV_IMG_DECLARE_FILE(ui_img_MCU);
    LV_IMG_DECLARE_FILE(ui_img_a1_series_png);
    LV_IMG_DECLARE_FILE(ui_img_Setlanguage);
    LV_IMG_DECLARE_FILE(ui_img_addprint);
    LV_IMG_DECLARE_FILE(ui_img_Axisdown);
    LV_IMG_DECLARE_FILE(ui_img_Axisup);
    LV_IMG_DECLARE_FILE(ui_img_cabin);
    LV_IMG_DECLARE_FILE(ui_img_Cali);
    LV_IMG_DECLARE_FILE(ui_img_colors);
    LV_IMG_DECLARE_FILE(ui_img_deleteprint);
    LV_IMG_DECLARE_FILE(ui_img_down);
    LV_IMG_DECLARE_FILE(ui_img_extrusion);
    LV_IMG_DECLARE_FILE(ui_img_exturder);
    LV_IMG_DECLARE_FILE(ui_img_fan);
    LV_IMG_DECLARE_FILE(ui_img_fanspeed);
    LV_IMG_DECLARE_FILE(ui_img_feedback);
    LV_IMG_DECLARE_FILE(ui_img_Hello);
    LV_IMG_DECLARE_FILE(ui_img_home);
    LV_IMG_DECLARE_FILE(ui_img_HomeAxis);
    LV_IMG_DECLARE_FILE(ui_img_HomeDebug);
    LV_IMG_DECLARE_FILE(ui_img_HomeFile);
    LV_IMG_DECLARE_FILE(ui_img_homefile1);
    LV_IMG_DECLARE_FILE(ui_img_HomePrint);
    LV_IMG_DECLARE_FILE(ui_img_HomeSet);
    LV_IMG_DECLARE_FILE(ui_img_hotbed);
    LV_IMG_DECLARE_FILE(ui_img_hotend);
    LV_IMG_DECLARE_FILE(ui_img_hotendyes);
    LV_IMG_DECLARE_FILE(ui_img_Language);
    LV_IMG_DECLARE_FILE(ui_img_Leveling);
    LV_IMG_DECLARE_FILE(ui_img_Light);
    LV_IMG_DECLARE_FILE(ui_img_Lightdown);
    LV_IMG_DECLARE_FILE(ui_img_lock);
    LV_IMG_DECLARE_FILE(ui_img_PID);
    LV_IMG_DECLARE_FILE(ui_img_reflash);
    LV_IMG_DECLARE_FILE(ui_img_resume);
    LV_IMG_DECLARE_FILE(ui_img_retrun);
    LV_IMG_DECLARE_FILE(ui_img_Setcolors);
    LV_IMG_DECLARE_FILE(ui_img_Setlight);
    LV_IMG_DECLARE_FILE(ui_img_Setlightdown);
    LV_IMG_DECLARE_FILE(ui_img_Setsystem);
    LV_IMG_DECLARE_FILE(ui_img_Setwifi);
    LV_IMG_DECLARE_FILE(ui_img_stop);
    LV_IMG_DECLARE_FILE(ui_img_stoprint);
    LV_IMG_DECLARE_FILE(ui_img_switch);
    LV_IMG_DECLARE_FILE(ui_img_tozero);
    LV_IMG_DECLARE_FILE(ui_img_updata);
    LV_IMG_DECLARE_FILE(ui_img_Withdrawal);
    LV_IMG_DECLARE_FILE(ui_img_Xadd);
    LV_IMG_DECLARE_FILE(ui_img_Xreduce);
    LV_IMG_DECLARE_FILE(ui_img_Yadd);
    LV_IMG_DECLARE_FILE(ui_img_Yreduce);
    LV_IMG_DECLARE_FILE(ui_img_Zadd);
    LV_IMG_DECLARE_FILE(ui_img_zero);
    LV_IMG_DECLARE_FILE(ui_img_Zreduce);
    LV_IMG_DECLARE_FILE(ui_img_switch_status);
    LV_IMG_DECLARE_FILE(ui_img_stl);
    LV_IMG_DECLARE_FILE(ui_img_timee);
    LV_IMG_DECLARE_FILE(ui_img_clean);
    LV_IMG_DECLARE_FILE(ui_img_config);    
    LV_IMG_DECLARE(up);
    LV_IMG_DECLARE(down);
    LV_IMG_DECLARE(PKQ);
#ifdef __cplusplus
} /*extern "C"*/
#endif
#endif
